import type { TreatmentFollowUpSuggestion } from '@/modules/institution/domain/treatment-followup-suggestions';
import { buildTreatmentFollowUpSuggestions } from '@/modules/institution/domain/treatment-followup-suggestions';
import type { TenantFollowUpTaskFromTreatmentSummarySuggestion } from '@/modules/institution/domain/followup-workflow';
import type { TreatmentSummaryRecord } from '@/modules/institution/domain/treatment-summaries';
import { mapTreatmentSummaryRecordToListItem } from '@/modules/institution/domain/treatment-summaries';
import { mapTreatmentSummaryListItemToFollowUpSuggestionInput, type TreatmentFollowUpSuggestionSelection } from '@/modules/institution/server/treatment-followup-suggestions';
import type { TenantBusinessRepository } from '@/modules/institution/server/tenant-business-repository';
import type { createTreatmentSummaryRepository } from '@/modules/institution/server/treatment-summary-repository';
type TreatmentSummaryRepository=ReturnType<typeof createTreatmentSummaryRepository>;
export type TreatmentFollowUpTaskConfirmationDto=Omit<TenantFollowUpTaskFromTreatmentSummarySuggestion,'tenantId'>;
export type TreatmentFollowUpSuggestionsForSummaryResult=|{kind:'success';summary:TreatmentSummaryRecord;suggestions:TreatmentFollowUpSuggestion[]}|{kind:'not_found'}|{kind:'voided';summary:TreatmentSummaryRecord};
export type ConfirmTreatmentFollowUpTaskResult=|{kind:'created';task:TreatmentFollowUpTaskConfirmationDto}|{kind:'not_found'}|{kind:'voided'}|{kind:'invalid_suggestion'}|{kind:'conflict';resourceId:string;reason:'active_source_follow_up_exists'};
export function mapFollowUpTaskConfirmationToDto(task:TenantFollowUpTaskFromTreatmentSummarySuggestion):TreatmentFollowUpTaskConfirmationDto{return{id:task.id,customerId:task.customerId,customerDisplayName:task.customerDisplayName,journeyId:task.journeyId,stage:task.stage,status:task.status,dueAt:task.dueAt,suggestedAction:task.suggestedAction,riskLevel:task.riskLevel,updatedBy:task.updatedBy,updatedAt:task.updatedAt,sourceTreatmentSummaryId:task.sourceTreatmentSummaryId,sourceSuggestionKey:task.sourceSuggestionKey};}
function buildSuggestionsForTreatmentSummary(summary:TreatmentSummaryRecord){return buildTreatmentFollowUpSuggestions(mapTreatmentSummaryListItemToFollowUpSuggestionInput(mapTreatmentSummaryRecordToListItem(summary)));}
function createFollowUpJourneyId(suggestion:TreatmentFollowUpSuggestion){return `treatment_followup_${suggestion.ruleKey}`.slice(0,96);}
export async function getTreatmentFollowUpSuggestionsForSummary(input:{tenantId:string;summaryId:string;treatmentSummaryRepository:Pick<TreatmentSummaryRepository,'getTreatmentSummaryByTenant'>}):Promise<TreatmentFollowUpSuggestionsForSummaryResult>{const summary=await input.treatmentSummaryRepository.getTreatmentSummaryByTenant({tenantId:input.tenantId,id:input.summaryId});if(!summary)return{kind:'not_found'};if(summary.status==='voided')return{kind:'voided',summary};return{kind:'success',summary,suggestions:buildSuggestionsForTreatmentSummary(summary)};}
export async function confirmTreatmentFollowUpTask(input:{tenantId:string;institutionId?:string|null;summaryId:string;selection:TreatmentFollowUpSuggestionSelection;treatmentSummaryRepository:Pick<TreatmentSummaryRepository,'getTreatmentSummaryByTenant'>;tenantBusinessRepository:Pick<TenantBusinessRepository,'createFollowUpTaskFromTreatmentSummarySuggestion'|'getCustomerByTenant'> & Partial<Pick<TenantBusinessRepository,'runCareFollowUpTransaction'>>}):Promise<ConfirmTreatmentFollowUpTaskResult>{
  const suggestionResult=await getTreatmentFollowUpSuggestionsForSummary({tenantId:input.tenantId,summaryId:input.summaryId,treatmentSummaryRepository:input.treatmentSummaryRepository});if(suggestionResult.kind==='not_found')return{kind:'not_found'};if(suggestionResult.kind==='voided')return{kind:'voided'};
  const suggestion=suggestionResult.suggestions.find(candidate=>candidate.suggestionKey===input.selection.suggestionKey);if(!suggestion)return{kind:'invalid_suggestion'};
  const customer=await input.tenantBusinessRepository.getCustomerByTenant({tenantId:input.tenantId,id:suggestionResult.summary.customerId});if(!customer)return{kind:'not_found'};
  const runner=input.tenantBusinessRepository.runCareFollowUpTransaction;
  if(typeof runner==='function'){const institutionId=input.institutionId??customer.institutionId??null;if(!institutionId)return{kind:'not_found'};const result=await runner(({commandService})=>commandService.createTreatmentSourceTask({attribution:{tenantId:input.tenantId,institutionId},task:{id:globalThis.crypto.randomUUID(),customerId:suggestionResult.summary.customerId,journeyId:createFollowUpJourneyId(suggestion),stage:suggestion.title,status:'scheduled',dueAt:suggestion.recommendedDueAt,suggestedAction:suggestion.description,riskLevel:suggestion.riskLevel,sourceTreatmentSummaryId:suggestion.sourceTreatmentSummaryId,sourceSuggestionKey:suggestion.suggestionKey}}));if(result.kind==='not_found_or_not_owned')return{kind:'not_found'};if(result.kind==='conflict')return result;return{kind:'created',task:{id:result.task.id,customerId:result.task.customerId,customerDisplayName:result.task.customerDisplayName,journeyId:result.task.journeyId,stage:result.task.stage,status:result.task.status,dueAt:result.task.dueAt,suggestedAction:result.task.suggestedAction,riskLevel:result.task.riskLevel,updatedBy:result.task.updatedBy,updatedAt:result.task.updatedAt,sourceTreatmentSummaryId:result.task.sourceTreatmentSummaryId??'',sourceSuggestionKey:result.task.sourceSuggestionKey??''}};}
  if(process.env.NODE_ENV!=='test')throw new Error('care_follow_up_transaction_runner_required');const legacyWriter=Reflect.get(input.tenantBusinessRepository,'createFollowUpTaskFromTreatmentSummarySuggestion') as TenantBusinessRepository['createFollowUpTaskFromTreatmentSummarySuggestion'];const result=await legacyWriter({id:globalThis.crypto.randomUUID(),tenantId:input.tenantId,customerId:suggestionResult.summary.customerId,customerDisplayName:customer.displayName,journeyId:createFollowUpJourneyId(suggestion),stage:suggestion.title,status:'scheduled',dueAt:suggestion.recommendedDueAt,suggestedAction:suggestion.description,riskLevel:suggestion.riskLevel,sourceTreatmentSummaryId:suggestion.sourceTreatmentSummaryId,sourceSuggestionKey:suggestion.suggestionKey});if(result.kind==='invalid_source')return{kind:'not_found'};if(result.kind==='conflict')return result;return{kind:'created',task:mapFollowUpTaskConfirmationToDto(result.task)};
}
