import { describe, expect, it, vi } from 'vitest';
import { createInstitutionKnowledgeCommandRepository } from '@/modules/knowledge/server/institution-knowledge-command-repository';
import type { TenantDatabase } from '@/server/db/client';
type Rows=unknown[];
function chain(rows:Rows){const c:any={};c.from=vi.fn(()=>c);c.where=vi.fn(()=>c);c.limit=vi.fn(async()=>rows);c.values=vi.fn(()=>c);c.set=vi.fn(()=>c);c.returning=vi.fn(async()=>rows);c.then=(onfulfilled:any,onrejected:any)=>Promise.resolve(rows).then(onfulfilled,onrejected);return c;}
function db(input?:{selectRows?:Rows[];insertRows?:Rows[];updateRows?:Rows[]}){const s=[...(input?.selectRows??[])],i=[...(input?.insertRows??[])],u=[...(input?.updateRows??[])];const d={select:vi.fn(()=>chain(s.shift()??[])),insert:vi.fn(()=>chain(i.shift()??[])),update:vi.fn(()=>chain(u.shift()??[]))};return{database:d as unknown as TenantDatabase,select:d.select,insert:d.insert,update:d.update};}
const document={id:'knowledge-a',tenantId:'tenant-a',institutionId:'inst-a',workspaceId:'inst-a',sourceId:'source-a',sourceKind:'seed',status:'ready',readonlyStatus:'readonly',title:'旧标题',version:'v1',createdAt:new Date('2026-08-10T00:00:00.000Z'),updatedAt:new Date('2026-08-10T00:00:00.000Z')};
const source={id:'source-a',tenantId:'tenant-a',institutionId:'inst-a',workspaceId:'inst-a',sourceKind:'seed',status:'ready',readonlyStatus:'readonly',sourceLabel:'旧分类',createdAt:new Date('2026-08-10T00:00:00.000Z'),updatedAt:new Date('2026-08-10T00:00:00.000Z')};
describe('Knowledge institution content command repository',()=>{
  it('fails closed before create when institution scope is not active',async()=>{const x=db({selectRows:[[]]});const r=createInstitutionKnowledgeCommandRepository(x.database);await expect(r.createItem({tenantId:'tenant-a',institutionId:'inst-a',title:'护理知识',category:'护理',description:'v1'})).resolves.toEqual({kind:'invalid_reference',reason:'institution_not_found_or_inactive'});expect(x.insert).not.toHaveBeenCalled();});
  it('creates source document and visibility after active institution validation',async()=>{const x=db({selectRows:[[{tenantId:'tenant-a',institutionId:'inst-a'}]],insertRows:[[],[],[]]});const r=createInstitutionKnowledgeCommandRepository(x.database);expect((await r.createItem({tenantId:'tenant-a',institutionId:'inst-a',title:'护理知识',category:'护理',description:'v1'})).kind).toBe('created');expect(x.insert).toHaveBeenCalledTimes(3);});
  it('returns stale conflict without issuing update',async()=>{const x=db({selectRows:[[document],[source]]});const r=createInstitutionKnowledgeCommandRepository(x.database);await expect(r.updateItem({tenantId:'tenant-a',institutionId:'inst-a',knowledgeId:'knowledge-a',expectedUpdatedAt:'2026-08-10T00:00:01.000Z',title:'新标题',category:'新分类',description:'v2'})).resolves.toEqual({kind:'conflict',knowledgeId:'knowledge-a',reason:'stale_update'});expect(x.update).not.toHaveBeenCalled();});
  it('updates document CAS first and source',async()=>{const updatedAt=new Date('2026-08-10T00:01:00.000Z');const x=db({selectRows:[[document],[source]],updateRows:[[{id:'knowledge-a',updatedAt}],[{id:'source-a'}]]});const r=createInstitutionKnowledgeCommandRepository(x.database);await expect(r.updateItem({tenantId:'tenant-a',institutionId:'inst-a',knowledgeId:'knowledge-a',expectedUpdatedAt:'2026-08-10T00:00:00.000Z',title:'新标题',category:'新分类',description:'v2'})).resolves.toEqual({kind:'updated',knowledgeId:'knowledge-a',updatedAt:updatedAt.toISOString()});expect(x.update).toHaveBeenCalledTimes(2);});
  it('returns CAS conflict before source mutation if document loses race',async()=>{const x=db({selectRows:[[document],[source]],updateRows:[[]]});const r=createInstitutionKnowledgeCommandRepository(x.database);await expect(r.updateItem({tenantId:'tenant-a',institutionId:'inst-a',knowledgeId:'knowledge-a',expectedUpdatedAt:'2026-08-10T00:00:00.000Z',title:'新标题',category:'新分类',description:'v2'})).resolves.toEqual({kind:'conflict',knowledgeId:'knowledge-a',reason:'stale_update'});expect(x.update).toHaveBeenCalledTimes(1);});
  it('archives document source and files after document CAS',async()=>{const updatedAt=new Date('2026-08-10T00:02:00.000Z');const x=db({selectRows:[[document],[source]],updateRows:[[{id:'knowledge-a',updatedAt}],[{id:'source-a'}],[]]});const r=createInstitutionKnowledgeCommandRepository(x.database);await expect(r.archiveItem({tenantId:'tenant-a',institutionId:'inst-a',knowledgeId:'knowledge-a',expectedUpdatedAt:'2026-08-10T00:00:00.000Z'})).resolves.toEqual({kind:'archived',knowledgeId:'knowledge-a',updatedAt:updatedAt.toISOString()});expect(x.update).toHaveBeenCalledTimes(3);});
});
