import { describe, expect, it, vi } from 'vitest';
import { readScopedConversationCommandRecordV1 } from '@/modules/institution-conversations/server/conversation-command-repository';
import type { TenantDatabase } from '@/server/db/client';
import { conversationAssignments, conversationRisks, conversationSegments, conversations } from '@/server/db/schema';
const scope = { tenantId: 'tenant-a', institutionId: 'institution-a', conversationId: 'conversation-a', segmentId: 'segment-a' } as const;
const root = () => ({ ...scope, id: scope.conversationId, activeSegmentId: scope.segmentId, lastClosedSegmentId: null, lastSegmentClosedAt: null, lastClosedSegmentInboundMessageId: null, lastClosedSegmentInboundAt: null, lastClosedSegmentInboundRevision: null, revision: 3, updatedAt: new Date('2026-08-19T01:03:00.000Z') });
const segment = () => ({ ...scope, id: scope.segmentId, sequenceNo: 1, state: 'awaiting_human', currentHandlerId: null, everHumanHandled: false, openedByCustomerMessageId: 'message-a', openedAt: new Date('2026-08-19T01:00:00.000Z'), lastCustomerMessageId: 'message-a', lastCustomerMessageAt: new Date('2026-08-19T01:00:00.000Z'), latestInboundRevision: 1, waitingAfterCustomerMessageId: null, waitingAfterCustomerMessageAt: null, waitingAfterInboundRevision: null, stateChangedAt: new Date('2026-08-19T01:01:00.000Z'), closedAt: null, segmentCloseKind: 'open', resolutionState: 'open', resolvedAt: null, blockingReasonCodes: [], revision: 3, updatedAt: new Date('2026-08-19T01:03:00.000Z') });
function dbMock(hasRisk: boolean) { const limit = vi.fn(async () => hasRisk ? [{ riskId: 'risk-a' }] : []); const select = vi.fn(() => ({ from(table: unknown) { if (table === conversations) return { where: vi.fn(async () => [root()]) }; if (table === conversationSegments) return { where: vi.fn(async () => [segment()]) }; if (table === conversationAssignments) return { where: vi.fn(() => ({ orderBy: vi.fn(async () => []) })) }; if (table === conversationRisks) return { where: vi.fn(() => ({ limit })) }; throw new Error('unexpected_select_table'); } })); return { database: { select } as unknown as TenantDatabase, limit }; }
describe('Conversation canonical risk readiness', () => { it('projects exact scoped risk existence without exposing risk content', async () => { const risky = dbMock(true); const clear = dbMock(false); const a = await readScopedConversationCommandRecordV1(risky.database, { tenantId: scope.tenantId, institutionId: scope.institutionId, conversationId: scope.conversationId }); const b = await readScopedConversationCommandRecordV1(clear.database, { tenantId: scope.tenantId, institutionId: scope.institutionId, conversationId: scope.conversationId }); expect(a?.segment?.hasRiskFacts).toBe(true); expect(b?.segment?.hasRiskFacts).toBe(false); expect(risky.limit).toHaveBeenCalledWith(1); expect(clear.limit).toHaveBeenCalledWith(1); }); });
