import { randomUUID } from 'node:crypto';
import { and, eq } from 'drizzle-orm';
import type { ArchiveInstitutionKnowledgeItemResult, CreateInstitutionKnowledgeItemResult, InstitutionKnowledgeCommandRepository, KnowledgeItemCommandAttribution, UpdateInstitutionKnowledgeItemResult } from '@/modules/knowledge/application/institution/knowledge-item-command-service';
import type { TenantDatabase } from '@/server/db/client';
import { institutionScopes, knowledgeDocumentFiles, knowledgeDocuments, knowledgeSources, platformKnowledgeInstitutionVisibility } from '@/server/db/schema';
type KnowledgeDocumentRow = typeof knowledgeDocuments.$inferSelect;
type KnowledgeSourceRow = typeof knowledgeSources.$inferSelect;
function newId(prefix:string){ return `${prefix}-${randomUUID()}`; }
async function hasActiveInstitutionScope(database:TenantDatabase,input:KnowledgeItemCommandAttribution){ const [scope]=await database.select({tenantId:institutionScopes.tenantId,institutionId:institutionScopes.institutionId}).from(institutionScopes).where(and(eq(institutionScopes.tenantId,input.tenantId),eq(institutionScopes.institutionId,input.institutionId),eq(institutionScopes.status,'active'))).limit(1); return Boolean(scope); }
async function findOwnedDocument(database:TenantDatabase,input:KnowledgeItemCommandAttribution&Readonly<{knowledgeId:string}>):Promise<KnowledgeDocumentRow|null>{ const [row]=await database.select().from(knowledgeDocuments).where(and(eq(knowledgeDocuments.tenantId,input.tenantId),eq(knowledgeDocuments.institutionId,input.institutionId),eq(knowledgeDocuments.id,input.knowledgeId))).limit(1); return row??null; }
async function findOwnedSource(database:TenantDatabase,input:KnowledgeItemCommandAttribution&Readonly<{sourceId:string}>):Promise<KnowledgeSourceRow|null>{ const [row]=await database.select().from(knowledgeSources).where(and(eq(knowledgeSources.tenantId,input.tenantId),eq(knowledgeSources.institutionId,input.institutionId),eq(knowledgeSources.id,input.sourceId))).limit(1); return row??null; }
function isStale(row:KnowledgeDocumentRow,expected:string){ return row.updatedAt.toISOString()!==expected; }
export function createInstitutionKnowledgeCommandRepository(database:TenantDatabase):InstitutionKnowledgeCommandRepository { return Object.freeze({
  async createItem(input:Parameters<InstitutionKnowledgeCommandRepository['createItem']>[0]):Promise<CreateInstitutionKnowledgeItemResult>{ if(!await hasActiveInstitutionScope(database,input)) return {kind:'invalid_reference',reason:'institution_not_found_or_inactive'}; const sourceId=newId('knowledge-source'); const knowledgeId=newId('knowledge-doc'); await database.insert(knowledgeSources).values({id:sourceId,tenantId:input.tenantId,institutionId:input.institutionId,workspaceId:input.institutionId,sourceKind:'seed',status:'ready',readonlyStatus:'readonly',sourceLabel:input.category}); await database.insert(knowledgeDocuments).values({id:knowledgeId,tenantId:input.tenantId,institutionId:input.institutionId,workspaceId:input.institutionId,sourceId,sourceKind:'seed',status:'ready',readonlyStatus:'readonly',title:input.title,version:input.description}); await database.insert(platformKnowledgeInstitutionVisibility).values({id:newId('knowledge-vis'),tenantId:input.tenantId,knowledgeDocumentId:knowledgeId,institutionId:input.institutionId}); return {kind:'created',sourceId,knowledgeId}; },
  async updateItem(input:Parameters<InstitutionKnowledgeCommandRepository['updateItem']>[0]):Promise<UpdateInstitutionKnowledgeItemResult>{ const current=await findOwnedDocument(database,input); if(!current) return {kind:'not_found_or_not_owned'}; const source=await findOwnedSource(database,{tenantId:input.tenantId,institutionId:input.institutionId,sourceId:current.sourceId}); if(!source) return {kind:'not_found_or_not_owned'}; if(isStale(current,input.expectedUpdatedAt)) return {kind:'conflict',knowledgeId:input.knowledgeId,reason:'stale_update'}; const nextUpdatedAt=new Date(); const [updatedDocument]=await database.update(knowledgeDocuments).set({title:input.title,version:input.description,updatedAt:nextUpdatedAt}).where(and(eq(knowledgeDocuments.tenantId,input.tenantId),eq(knowledgeDocuments.institutionId,input.institutionId),eq(knowledgeDocuments.id,input.knowledgeId),eq(knowledgeDocuments.sourceId,source.id),eq(knowledgeDocuments.updatedAt,new Date(input.expectedUpdatedAt)))).returning({id:knowledgeDocuments.id,updatedAt:knowledgeDocuments.updatedAt}); if(!updatedDocument) return {kind:'conflict',knowledgeId:input.knowledgeId,reason:'stale_update'}; const [updatedSource]=await database.update(knowledgeSources).set({sourceLabel:input.category,updatedAt:nextUpdatedAt}).where(and(eq(knowledgeSources.tenantId,input.tenantId),eq(knowledgeSources.institutionId,input.institutionId),eq(knowledgeSources.id,source.id))).returning({id:knowledgeSources.id}); if(!updatedSource) throw new Error('knowledge_source_update_failed'); return {kind:'updated',knowledgeId:updatedDocument.id,updatedAt:updatedDocument.updatedAt.toISOString()}; },
  async archiveItem(input:Parameters<InstitutionKnowledgeCommandRepository['archiveItem']>[0]):Promise<ArchiveInstitutionKnowledgeItemResult>{ const current=await findOwnedDocument(database,input); if(!current) return {kind:'not_found_or_not_owned'}; const source=await findOwnedSource(database,{tenantId:input.tenantId,institutionId:input.institutionId,sourceId:current.sourceId}); if(!source) return {kind:'not_found_or_not_owned'}; if(isStale(current,input.expectedUpdatedAt)) return {kind:'conflict',knowledgeId:input.knowledgeId,reason:'stale_update'}; if(current.status==='disabled'||current.readonlyStatus==='blocked') return {kind:'conflict',knowledgeId:input.knowledgeId,reason:'invalid_state'}; const archivedAt=new Date(); const [archivedDocument]=await database.update(knowledgeDocuments).set({status:'disabled',readonlyStatus:'blocked',updatedAt:archivedAt}).where(and(eq(knowledgeDocuments.tenantId,input.tenantId),eq(knowledgeDocuments.institutionId,input.institutionId),eq(knowledgeDocuments.id,input.knowledgeId),eq(knowledgeDocuments.sourceId,source.id),eq(knowledgeDocuments.updatedAt,new Date(input.expectedUpdatedAt)),eq(knowledgeDocuments.status,current.status),eq(knowledgeDocuments.readonlyStatus,current.readonlyStatus))).returning({id:knowledgeDocuments.id,updatedAt:knowledgeDocuments.updatedAt}); if(!archivedDocument) return {kind:'conflict',knowledgeId:input.knowledgeId,reason:'stale_update'}; const [archivedSource]=await database.update(knowledgeSources).set({status:'disabled',readonlyStatus:'blocked',updatedAt:archivedAt}).where(and(eq(knowledgeSources.tenantId,input.tenantId),eq(knowledgeSources.institutionId,input.institutionId),eq(knowledgeSources.id,source.id))).returning({id:knowledgeSources.id}); if(!archivedSource) throw new Error('knowledge_source_archive_failed'); await database.update(knowledgeDocumentFiles).set({status:'archived',archivedAt,updatedAt:archivedAt}).where(and(eq(knowledgeDocumentFiles.tenantId,input.tenantId),eq(knowledgeDocumentFiles.knowledgeDocumentId,input.knowledgeId))); return {kind:'archived',knowledgeId:archivedDocument.id,updatedAt:archivedDocument.updatedAt.toISOString()}; },
}); }
